// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var GetKeycodeDefinitionsJs = require("./getKeycodeDefinitions.js");

function getKeycodeDefinition(prim) {
  return GetKeycodeDefinitionsJs.getKeycodeDefinition(prim);
}

exports.getKeycodeDefinition = getKeycodeDefinition;
/* ./getKeycodeDefinitions.js Not a pure module */
